stages:
  data_handling:
    cmd: >
      python future_sales_prediction_2024/data_handling.py
      --items local_storage/raw_data/items.csv
      --categories local_storage/raw_data/item_categories.csv
      --train local_storage/raw_data/sales_train.csv
      --shops local_storage/raw_data/shops.csv
      --test local_storage/raw_data/test.csv
    deps:
      - future_sales_prediction_2024/data_handling.py
      - local_storage/raw_data/items.csv
      - local_storage/raw_data/item_categories.csv
      - local_storage/raw_data/sales_train.csv
      - local_storage/raw_data/shops.csv
      - local_storage/raw_data/test.csv
    outs:
      - local_storage/preprocessed_data/full_data.csv
      - local_storage/preprocessed_data/train.csv


  feature_extraction:
    cmd: >
      python future_sales_prediction_2024/feature_extraction.py
      --full_data local_storage/preprocessed_data/full_data.csv
      --train local_storage/preprocessed_data/train.csv
    deps:
      - future_sales_prediction_2024/feature_extraction.py
      - local_storage/preprocessed_data/full_data.csv
      - local_storage/preprocessed_data/train.csv
    outs:
      - local_storage/preprocessed_data/full_featured_data.csv