stages:
  data_handling:
    cmd: >
      python future_sales_prediction_2024/core/data_handling.py
      --items gs://my-dvc-bucket_future_prections/raw_data/items.csv
      --categories gs://my-dvc-bucket_future_prections/raw_data/item_categories.csv
      --train gs://my-dvc-bucket_future_prections/raw_data/sales_train.csv
      --shops gs://my-dvc-bucket_future_prections/raw_data/shops.csv
      --test gs://my-dvc-bucket_future_prections/raw_data/test.csv
      --outdir gs://my-dvc-bucket_future_prections/preprocessed_data
    deps:
      - future_sales_prediction_2024/core/data_handling.py
      - gs://my-dvc-bucket_future_prections/raw_data/items.csv
      - gs://my-dvc-bucket_future_prections/raw_data/item_categories.csv
      - gs://my-dvc-bucket_future_prections/raw_data/sales_train.csv
      - gs://my-dvc-bucket_future_prections/raw_data/shops.csv
      - gs://my-dvc-bucket_future_prections/raw_data/test.csv
    outs:
      - gs://my-dvc-bucket_future_prections/preprocessed_data/full_data.csv:
          cache: false
      - gs://my-dvc-bucket_future_prections/preprocessed_data/train.csv:
          cache: false


  feature_extraction:
    cmd: >
      python future_sales_prediction_2024/core/feature_extraction.py
      --full_data gs://my-dvc-bucket_future_prections/preprocessed_data/full_data.csv
      --train gs://my-dvc-bucket_future_prections/preprocessed_data/train.csv
      --outdir gs://my-dvc-bucket_future_prections/preprocessed_data
    deps:
      - future_sales_prediction_2024/core/feature_extraction.py
      - gs://my-dvc-bucket_future_prections/preprocessed_data/full_data.csv
      - gs://my-dvc-bucket_future_prections/preprocessed_data/train.csv
    outs:
      - gs://my-dvc-bucket_future_prections/preprocessed_data/full_featured_data.csv:
          cache: false